/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import control.JugadorData;
import control.PartidoData;
import control.TorneoData;
import java.util.ArrayList;
import modelo.Jugador;
import modelo.Partido;
import modelo.Torneo;

/**
 *
 * @author FP
 */
public class ListarTorneosPorJugador extends javax.swing.JInternalFrame {
    private TorneoData torneoData;
    private PartidoData partidoData;
    private JugadorData jugadorData;
        
    
    private ArrayList<Jugador> listaJugadores = new ArrayList<>();
    private ArrayList<Torneo> listaTorneos = new ArrayList<>();
    private ArrayList<Partido> listaPartidos = new ArrayList<>();
    private Partido partido;
    
    /** Creates new form ListarTorneosPorJugador */
    public ListarTorneosPorJugador() {
        initComponents();
    }
    
     public ListarTorneosPorJugador(TorneoData torneoData, PartidoData partidoData, JugadorData jugadorData){

        initComponents();
        
        this.torneoData = torneoData;
        this.partidoData = partidoData;
        this.jugadorData = jugadorData;

       llenarComboJugadores(true);
       llenarListaTorneos((Jugador) cbJugadores.getSelectedItem());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbJugadores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTorneos = new javax.swing.JList<>();

        setTitle("Torneos por Jugador");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lista de Torneos por Jugador");

        cbJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJugadoresActionPerformed(evt);
            }
        });

        jLabel2.setText("Jugadores:");

        jLabel3.setText("Torneos:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstTorneos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJugadoresActionPerformed
        llenarListaTorneos((Jugador) cbJugadores.getSelectedItem());
    }//GEN-LAST:event_cbJugadoresActionPerformed

    private void llenarListaTorneos(Jugador jugador){
       
        listaTorneos = (ArrayList) partidoData.obtenerTorneosPorJugador(jugador);
        lstTorneos.removeAll();

        int largoLista = listaTorneos.size();
        
        //    String[] apellidoNombre = new String[largoLista];
        Torneo[] nombre = new Torneo[largoLista];
        int i = 0;

        for (Torneo torneo : listaTorneos) {
           
                nombre[i] = torneo;
              i++;
           
        }

        lstTorneos.setModel(new javax.swing.AbstractListModel<Torneo>() {
            public int getSize() {
                return listaTorneos.size();
            }

            public Torneo getElementAt(int i) {
                return nombre[i];
            }
        });
    }
    
    private void llenarComboJugadores(Boolean activo){
     listaJugadores = (ArrayList) jugadorData.obtenerJugador();
        int largoLista = listaJugadores.size();
        Jugador[] nombre = new Jugador[largoLista];

        int i = 0;

        for (Jugador jugador : listaJugadores) {
            if (jugador.isActivo() == activo) {
                cbJugadores.addItem(jugador);
                i++;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Jugador> cbJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Torneo> lstTorneos;
    // End of variables declaration//GEN-END:variables

}
